version: '3.8'

services:
  db:
    image: postgres:15
    container_name: gallus_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
    
