version: '3.8'

services:
  db:
    image: postgres:15
    container_name: gallus_db
    environment:
      POSTGRES_DB: gallus
      POSTGRES_USER: lenard
      POSTGRES_PASSWORD: secret123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
    
